"""
This module is a re-exporter for the props submodules.

DO NOT EDIT THIS FILE DIRECTLY. Edit the individual submodules instead.
"""

from map._props.coffin import Coffin
from map._props.dias import Dias
from map._props.rock import Rock
from map._props.altar import Altar
from map._props.column import Column, ColumnType
from map._props.fountain import Fountain
from map._props.stairs import StairsProp

__all__ = [ "Coffin", "Dias", "Rock", "Altar", "Column", "ColumnType", "Fountain", "StairsProp" ]
