"""
This module is a re-exporter for the props submodules.

DO NOT EDIT THIS FILE DIRECTLY. Edit the individual submodules instead.
"""

from map._props.coffin import Coffin
from map._props.dais import Dais
from map._props.rock import Rock
from map._props.altar import Altar
from map._props.column import Column, ColumnType

__all__ = [ "Coffin", "Dais", "Rock", "Altar", "Column", "ColumnType" ]
